// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetGopherOKCode is the HTTP code returned for type GetGopherOK
const GetGopherOKCode int = 200

/*GetGopherOK Returns the Gopher.

swagger:response getGopherOK
*/
type GetGopherOK struct {

	/*
	  In: Body
	*/
	Payload io.ReadCloser `json:"body,omitempty"`
}

// NewGetGopherOK creates GetGopherOK with default headers values
func NewGetGopherOK() *GetGopherOK {

	return &GetGopherOK{}
}

// WithPayload adds the payload to the get gopher o k response
func (o *GetGopherOK) WithPayload(payload io.ReadCloser) *GetGopherOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get gopher o k response
func (o *GetGopherOK) SetPayload(payload io.ReadCloser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGopherOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
